// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// SPDX-FileCopyrightText: © 2026 Olivier Meunier <olivier@neokraft.net>

//

// SPDX-License-Identifier: AGPL-3.0-only

package assets

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import . "codeberg.org/readeck/readeck/components"

type feedXSLT struct{}

func (v feedXSLT) component() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templ.Raw(`<?xml version="1.0" encoding="utf-8"?>`+"\n").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\" xmlns:atom=\"http://www.w3.org/2005/Atom\" exclude-result-prefixes=\"atom\"><xsl:output method=\"html\" version=\"1.0\" encoding=\"UTF-8\" indent=\"yes\"></xsl:output> <xsl:template match=\"/\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>Feed - <xsl:value-of select=\"atom:feed/atom:title\"></xsl:value-of></title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(`<meta http-equiv="X-UA-Compatible" content="IE=edge"/>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(`<meta name="viewport" content="width=device-width, initial-scale=1.0"/>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(S(
			`<link rel="icon" href="%s" sizes="48x48"/>`,
			templ.EscapeString(Asset(ctx, "img/fi/favicon.ico")),
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(S(
			`<link rel="stylesheet" href="%s"/>`,
			templ.EscapeString(Asset(ctx, "bundle.css")),
		)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</head><body class=\"font-sans leading-tight tracking-normal max-w-col-14 mt-0 mb-12 mx-auto\"><section><div class=\"my-8 p-4 rounded bg-yellow-200\"><p><strong>This is a web feed</strong>, also known as an Atom feed. <strong>Subscribe</strong> by following the instructions below.</p></div></section><section class=\"mb-8\"><xsl:apply-templates select=\"atom:feed\"></xsl:apply-templates></section><section class=\"border-t pt-4\"><h2 class=\"title text-h3\">Feed's Items</h2><xsl:apply-templates select=\"atom:feed/atom:entry\"></xsl:apply-templates></section></body></html></xsl:template> <xsl:template match=\"atom:feed\"><h1 class=\"flex items-center gap-2 title text-h2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(`<img alt="" class="inline h-6 w-6 mb-0">`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<xsl:attribute name=\"src\"><xsl:value-of select=\"atom:icon\"></xsl:value-of></xsl:attribute>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(`</img>`).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<xsl:attribute name=\"src\"><xsl:value-of select=\"atom:icon\"></xsl:value-of></xsl:attribute> <span><xsl:value-of select=\"atom:title\"></xsl:value-of> • Web Feed Preview</span></h1><p class=\"mb-2\">This feed provides the latest entries from <xsl:value-of select=\"atom:title\"></xsl:value-of>.</p><p class=\"mb-2\">Subscribe to this feed by copying the URL below:</p><p class=\"mb-4\"><code><a class=\"link text-sm font-semibold\"><xsl:attribute name=\"href\"><xsl:value-of select=\"atom:link[@rel='self']/@href\"></xsl:value-of></xsl:attribute> <xsl:value-of select=\"atom:link[@rel='self']/@href\"></xsl:value-of></a></code></p><p class=\"my-4 p-4 rounded bg-red-100\"><strong>Access to this feed is restricted.</strong>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw("<br/> ").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "You must provide your newsreader app a username and an <a class=\"link\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(URL(ctx, "/profile/tokens"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/assets/x-feed-xslt.templ`, Line: 81, Col: 109}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\">API Token</a> to load this feed.</p><p class=\"text-center\"><a class=\"btn btn-outlined btn-primary\"><xsl:attribute name=\"href\"><xsl:value-of select=\"atom:link[@rel='alternate']/@href\"></xsl:value-of></xsl:attribute>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Icon("o-chevron-l", WithIconClass("inline-block"), WithIconSvgClass()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "Go back</a></p></xsl:template> <xsl:template match=\"atom:entry\"><div class=\"mb-4\"><h3 class=\"mb-1.5 text-lg font-semibold leading-none\"><a class=\"link\"><xsl:attribute name=\"href\"><xsl:value-of select=\"atom:link[@rel='alternate']/@href\"></xsl:value-of></xsl:attribute> <xsl:value-of select=\"atom:title\"></xsl:value-of></a></h3><p><xsl:value-of select=\"atom:summary\" disable-output-escaping=\"yes\"></xsl:value-of></p><small>Published: <xsl:value-of select=\"atom:updated\"></xsl:value-of></small></div></xsl:template></xsl:stylesheet>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
